### ISSUE TITLE
gradle compileKotlin command fails

### ISSUE THREAD

**Issue by hobbesthetige** [gradle-guides/building-kotlin-jvm-libraries#10]
I'm trying to follow along in the guide, but I can't get even the simplest gradle to compile. I have searched the world over for help but can't find much.

Gradle v. 4.4.1
JDK 9.0.1

Here is my gradle file (screenshot): 
<img width="612" alt="screen shot 2017-12-27 at 1 25 26 pm" src="https://user-images.githubusercontent.com/4026614/34389769-9b0f7ac0-eb09-11e7-8c85-73549301b183.png">

And here is my terminal output (screenshot):
<img width="1101" alt="screen shot 2017-12-27 at 1 25 59 pm" src="https://user-images.githubusercontent.com/4026614/34389776-a5affd9c-eb09-11e7-9d60-7c25e95ef6b6.png">

**Comment by hobbesthetige** [comment]
Sorry, I didn't realize that this guide has not been updated for new gradle syntax. I figured it all out. Thank you

**Comment by eriwen** [comment]
My mistake here. This is fixed now.
