### ISSUE TITLE
The part about bundling (or not bundling) the Kotlin runtime is missing

### ISSUE THREAD

**Issue by adam-arold** [gradle-guides/building-kotlin-jvm-libraries#13]
A lot of folks seem to struggle with that part and I think it is the single most important thing to do when you are authoring a Kotlin library. What is the canonical way of handling the Kotlin runtime dependency?

**Comment by lacasseio** [comment]
Issue moved to [gradle/guides #255](https://github.com/gradle/guides/issues/255) via [**ZenHub**](https://www.zenhub.com/)
