### ISSUE TITLE
Code coverage anyone?

### ISSUE THREAD

**Issue by pajatopmr** [gradle-guides/building-kotlin-jvm-libraries#6]
I have taken a quick scan to see if there is anything to support code coverage reports herein, ala JaCoCo.  Either I have missed them or there is no such support yet.  I suspect the latter.  If there is no such support yet, this is a serious shortcoming that needs some TLC.

**Comment by eriwen** [comment]
This guide is far from comprehensive. With Kotlin DSL v0.11, nearly everything in the Groovy DSL, including JaCoCo is supported. There just aren't many people using it yet. 

I'll take this as a suggestion to add some kind of example for this, in this guide or otherwise.

**Comment by lacasseio** [comment]
Issue moved to [gradle/guides #227](https://github.com/gradle/guides/issues/227) via [**ZenHub**](https://www.zenhub.com/)
